name: Daily Automation

on:
  schedule:
    # 每天北京时间 09:00 运行 (UTC+8 = 01:00 UTC)
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  daily-task:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        if [ -f "package.json" ]; then
          npm ci
        fi

    - name: Debug - detailed file listing
      run: |
        echo "===== Current workspace ====="
        pwd
        echo "===== Detailed file structure ====="
        find . -maxdepth 3 -type f | sort
        echo "===== Checking src/index.js specifically ====="
        if [ -f "src/index.js" ]; then
          echo "✅ src/index.js exists at $(pwd)/src/index.js"
          echo "File size: $(wc -l < src/index.js) lines"
          echo "First 5 lines:"
          head -5 src/index.js
        else
          echo "❌ src/index.js does not exist"
          echo "Available files in src/:"
          ls -la src/ || echo "src/ directory doesn't exist"
        fi

    - name: Run daily script
      env:
        JINA_API_KEY: ${{ secrets.JINA_API_KEY }}
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
        DEEPSEEK_MODEL: ${{ secrets.DEEPSEEK_MODEL }}
      run: |
        node src/index.js
